import type { Metadata } from "next";

import { LegalPage } from "../legal-page";
import { publicPageMetadata } from "@/lib/marketing/public-metadata";

export const metadata: Metadata = publicPageMetadata({
  title: "Terms of Service",
  description:
    "The terms that govern your use of sopher.ai — who owns the manuscripts you generate, how credits work, and what we do and do not permit.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="August 2, 2026">
      <p>
        <strong>Reader-link notice:</strong> the reader-link terms below take effect for you when
        you expressly opt into that optional feature after its sharing disclosure, and for everyone
        else on August 16, 2026.
      </p>
      <p>
        These terms govern your use of sopher.ai (&ldquo;the Service&rdquo;), operated by sopher.ai
        (&ldquo;we&rdquo;, &ldquo;us&rdquo;). By creating an account or buying credits you agree to
        them. If you do not agree, do not use the Service.
      </p>

      <h2>What the Service is</h2>
      <p>
        sopher.ai turns a written brief into a book-length manuscript using AI models, and provides
        tools to edit, review, and export the result. Output is generated by machine learning
        systems: it can be wrong, uneven, or unlike what you imagined, and identical prompts can
        produce different results. We do not promise that any output will be publishable, accurate,
        or fit for a particular purpose.
      </p>

      <h2>Your content and your rights</h2>
      <ul>
        <li>
          <strong>Your brief stays yours.</strong> You keep all rights to the material you provide.
        </li>
        <li>
          <strong>The manuscript is yours.</strong> To the maximum extent permitted by law, we
          assign to you all rights we may hold in output generated for your account. You may
          publish, sell, and adapt it without attribution to us.
        </li>
        <li>
          <strong>You are responsible for what you make.</strong> You must not use the Service to
          produce content that is unlawful, infringes others&rsquo; rights, or violates the
          acceptable-use rules of our model providers. Copyright treatment of AI-assisted works
          varies by jurisdiction; obtaining registration or protection is your responsibility.
        </li>
      </ul>

      <h2>How your content is processed</h2>
      <p>
        Your brief and manuscript text are sent to third-party AI model providers (currently
        Anthropic and Google, routed through Vercel&rsquo;s AI Gateway) to generate and edit your
        book. We use providers under terms that do not permit training on your content. Manuscripts
        are stored in our database and file storage so you can return to them; they are private to
        your account unless you deliberately create a reader link. A reader link makes one captured
        edition available to anyone who has its secret URL until it expires or you revoke it. You
        are responsible for choosing recipients and for anything they copy or redistribute from that
        edition.
      </p>

      <h2>Credits and payment</h2>
      <ul>
        <li>
          Credits are prepaid and consumed as work runs. One credit is one US dollar of retail
          value.
        </li>
        <li>Costs shown before a run are estimates; actual consumption is metered.</li>
        <li>
          Credits are not transferable, have no cash value, do not expire, and — as set out in the
          refund policy — are not refundable once purchased.
        </li>
        <li>Payments are processed by Stripe. We never see your card details.</li>
        <li>Refunds are governed by the refund policy, which is part of these terms.</li>
      </ul>

      <h2>Fair use of the Service</h2>
      <p>
        You may not resell access to the Service, probe or overload it, scrape it, attempt to
        extract our prompts or other users&rsquo; content, or use it to build a competing dataset.
        We may set reasonable rate limits.
      </p>

      <h2>Termination</h2>
      <p>
        You can delete your account at any time. We may suspend or terminate accounts that break
        these terms. Unspent credits are not refunded on deletion or termination. On deletion, your
        projects and manuscripts are removed from our systems as described in the privacy policy —
        export anything you want to keep first.
      </p>

      <h2>Disclaimers and liability</h2>
      <p>
        The Service is provided &ldquo;as is&rdquo;. To the maximum extent permitted by law, we
        disclaim all warranties, and our total liability to you for any claim is limited to the
        amount you paid us in the twelve months before the claim arose. Nothing in these terms
        excludes liability that cannot lawfully be excluded.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms. Material changes will be announced on this page with a new
        &ldquo;last updated&rdquo; date at least 14 days before they take effect; continuing to use
        the Service after that date is acceptance. You may choose to use a new optional feature
        sooner when its specific terms are disclosed and you expressly opt in.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms: <a href="mailto:support@sopher.ai">support@sopher.ai</a>.
      </p>
    </LegalPage>
  );
}
