apiVersion: v1
kind: Service
metadata:
  name: sopher-api-service
  namespace: sopher-ai
  labels:
    app: sopher-api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: sopher-api
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800