apiVersion: apps/v1
kind: Deployment
metadata:
  name: sopher-api
  namespace: sopher-ai
  labels:
    app: sopher-api
    tier: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sopher-api
  template:
    metadata:
      labels:
        app: sopher-api
        tier: backend
    spec:
      containers:
      - name: api
        image: ghcr.io/cheesejaguar/sopher-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: sopher-ai-config
        - secretRef:
            name: sopher-ai-secrets
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /livez
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      nodeSelector:
        workload: general
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "general"
        effect: "NoSchedule"