# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sopher-ai
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
