# PostgreSQL StatefulSet and Config
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: sopher-ai
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: false
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "sopherai"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: sopher-ai-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sopher-ai-secrets
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: postgres-init
        configMap:
          name: postgres-init
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: sopher-ai
data:
  init.sql: |
    -- Example: CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    -- Add custom initialization SQL here
