apiVersion: apps/v1
kind: Deployment
metadata:
  name: sopher-web
  namespace: sopher-ai
  labels:
    app: sopher-web
    tier: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sopher-web
  template:
    metadata:
      labels:
        app: sopher-web
        tier: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: web
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
        image: ghcr.io/cheesejaguar/sopher-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: BACKEND_URL
          value: "http://sopher-api-service:8000"
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "https://api.sopher.ai"
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: next-cache-volume
          mountPath: /.next
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 20
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: next-cache-volume
        emptyDir: {}