apiVersion: v1
kind: Service
metadata:
  name: sopher-web-service
  namespace: sopher-ai
  labels:
    app: sopher-web
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: sopher-web