name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write   # changed from read to allow deletions
      issues: write          # changed from read to allow deletions
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install GitHub CLI
        uses: cli/cli-action@v2

      - name: Cleanup previous Claude comments
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          AUTHOR_LOGIN: "github-actions[bot]"   # change to match your bot account
          MARKER: "[claude-review]"             # optional marker text to avoid deleting human comments
        run: |
          set -euo pipefail

          echo "Deleting prior ISSUE comments…"
          gh api repos/$REPO/issues/$PR_NUMBER/comments --paginate \
            --jq '.[] | select(.user.login=="'"$AUTHOR_LOGIN"'") | @json' | \
          while read -r c; do
            id=$(jq -r '.id' <<<"$c")
            body=$(jq -r '.body' <<<"$c")
            if [ -z "$MARKER" ] || grep -q "$MARKER" <<<"$body"; then
              echo "  Deleting issue comment $id"
              gh api -X DELETE repos/$REPO/issues/comments/$id
            fi
          done

          echo "Deleting prior REVIEW comments…"
          gh api repos/$REPO/pulls/$PR_NUMBER/comments --paginate \
            --jq '.[] | select(.user.login=="'"$AUTHOR_LOGIN"'") | @json' | \
          while read -r c; do
            id=$(jq -r '.id' <<<"$c")
            body=$(jq -r '.body' <<<"$c")
            if [ -z "$MARKER" ] || grep -q "$MARKER" <<<"$body"; then
              echo "  Deleting review comment $id"
              gh api -X DELETE repos/$REPO/pulls/comments/$id
            fi
          done

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4.1)
          # model: "claude-opus-4-1-20250805"

          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            [claude-review]  
            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage
            
            Be constructive and helpful in your feedback.